# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 16:04
from __future__ import unicode_literals

import AWD_Zanasi.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sigla', models.CharField(max_length=16)),
                ('Help_ENG', models.CharField(blank=True, max_length=400, null=True)),
                ('Help', models.CharField(blank=True, max_length=400, null=True)),
                ('Tipo_di_Ramo', models.CharField(blank=True, max_length=16, null=True)),
                ('Diretto', models.CharField(blank=True, max_length=16, null=True)),
                ('Out', models.CharField(blank=True, max_length=16, null=True)),
                ('E_name', models.CharField(blank=True, max_length=16, null=True)),
                ('K_name', models.CharField(blank=True, max_length=16, null=True)),
                ('Q_name', models.CharField(blank=True, max_length=16, null=True)),
                ('F_name', models.CharField(blank=True, max_length=16, null=True)),
                ('Comandi', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommandBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sigla', models.CharField(max_length=16)),
                ('Help_ENG', models.CharField(blank=True, max_length=400, null=True)),
                ('Help', models.CharField(blank=True, max_length=400, null=True)),
                ('Nome', models.CharField(blank=True, max_length=16, null=True)),
                ('Value', models.CharField(blank=True, max_length=16, null=True)),
                ('StrNum', models.CharField(blank=True, max_length=16, null=True)),
                ('Vincoli', models.CharField(blank=True, max_length=16, null=True)),
                ('Range', models.CharField(blank=True, max_length=48, null=True)),
                ('Type', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='project', max_length=200)),
                ('matlab_file', models.FileField(upload_to=AWD_Zanasi.models.user_directory_path)),
                ('proj_desc', models.CharField(blank=True, max_length=400, null=True)),
                ('launch_date', models.DateField(blank=True, null=True, verbose_name='Launch Date')),
                ('user', models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_file', models.FileField(blank=True, null=True, upload_to='matlab_projects/%Y/%m/%d/')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='matlab_projects/%Y/%m/%d/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AWD_Zanasi.Project')),
            ],
        ),
        migrations.CreateModel(
            name='CommandSystem',
            fields=[
                ('commandbranch_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='AWD_Zanasi.CommandBranch')),
            ],
            options={
                'abstract': False,
            },
            bases=('AWD_Zanasi.commandbranch',),
        ),
    ]
