# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matlab_file', models.FileField(upload_to='matlab_projects/%Y/%m/%d/')),
                ('proj_desc', models.CharField(max_length=400)),
                ('res_type', models.CharField(max_length=3, verbose_name='Resolution Type')),
                ('launch_date', models.DateField(verbose_name='Launch Date')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.TextField()),
                ('img', models.ImageField(upload_to=b'')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AWD_Zanasi.Project')),
            ],
        ),
    ]
