# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 11:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matlab_file', models.FileField(upload_to='matlab_projects/%Y/%m/%d/')),
                ('proj_desc', models.CharField(blank=True, max_length=400, null=True)),
                ('res_type', models.CharField(max_length=3, verbose_name='Resolution Type')),
                ('launch_date', models.DateField(blank=True, null=True, verbose_name='Launch Date')),
                ('user', models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AWD_Zanasi.Project')),
            ],
        ),
    ]
