# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AWD_Zanasi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project_Output',
            new_name='ProjectOutput',
        ),
    ]
